**Implementing Gradient Descent for n featrue data set. df will be of (m*n)**

In [28]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [29]:
def slope(data,y,row,col,m,j):
    m_slope=0
    M=len(data)
    for i in range(row):
        y1=y[i]
        for k in range(col):
            m_slope+=(-2/M)*(y1-(m[k]*data[i][k]))*data[i][j]
    return m_slope        

In [30]:
def step_gd(data,y,row,col,m,lr):
    # x=data[:,:3]
    m_new=np.zeros(col)
    for j in range(col):
        m_new[j]=m[j]-lr*slope(data,y,row,col,m,j)
    return m_new    


In [31]:
def cost(data,y,m,row,col):
    M=len(data)
    total_cost=0
    for i in range(row):
        for j in range(col):
            total_cost+=(1/M)*(((y[i])-m[j]*data[i][j])**2)
    return total_cost

In [32]:
def gd(data,it,lr):
    row,col=data.shape
    m=np.zeros(col)
    y=data[:,col-1].copy()
    data[:,col-1]=np.ones(row)
    for i in range(it):
      m=step_gd(data,y,row,col,m,lr)
      print("Cost-:",cost(data,y,m,row,col))
    return m[:col-1],m[col-1]    
    

In [63]:
data_train=np.loadtxt('train.csv',delimiter=',',encoding='utf-8-sig')
learning_rate=0.001
num_iterations=40
m,c=gd(data_train,num_iterations,learning_rate)
print(m,c)

Cost-: 8348.622165251922
Cost-: 8310.804014956142
Cost-: 8274.242258750546
Cost-: 8238.922116049456
Cost-: 8204.829077317176
Cost-: 8171.948897693787
Cost-: 8140.267590778717
Cost-: 8109.77142256835
Cost-: 8080.446905543888
Cost-: 8052.280792905574
Cost-: 8025.2600729497235
Cost-: 7999.371963585006
Cost-: 7974.603906984475
Cost-: 7950.943564370133
Cost-: 7928.378810926447
Cost-: 7906.897730839746
Cost-: 7886.488612460464
Cost-: 7867.139943585096
Cost-: 7848.840406854739
Cost-: 7831.578875267569
Cost-: 7815.344407802293
Cost-: 7800.126245149598
Cost-: 7785.9138055496105
Cost-: 7772.696680731697
Cost-: 7760.464631954822
Cost-: 7749.207586145922
Cost-: 7738.91563213338
Cost-: 7729.57901697353
Cost-: 7721.188142368287
Cost-: 7713.733561170558
Cost-: 7707.205973976424
Cost-: 7701.5962258011095
Cost-: 7696.895302837154
Cost-: 7693.094329292397
Cost-: 7690.184564305776
Cost-: 7688.157398939639
Cost-: 7687.004353245584
Cost-: 7686.7170734028805
Cost-: 7687.2873289275085
Cost-: 7688.70700994946

In [34]:
def predict(data,m,c):
    y_pred=np.zeros(len(data))
    for i in range(len(data)):
        y_pred[i]=((m*data[i,:]).sum()+c)
    return y_pred    

In [35]:
x_test=np.loadtxt('test.csv',delimiter=',',encoding='utf-8-sig')

In [64]:
y_pred=predict(x_test,m,c)

In [65]:
y_pred

array([-27.2244541 ,  48.01151125,  23.02841602,  46.16125564,
        22.45352301, -23.65033208,  45.53971476,  34.20732119,
        19.82305334,  31.38677978,  38.98317507,  18.71438487,
        35.97914519,  28.87885447,  63.16419209,  46.68189413,
        38.95036825,  39.45667779,  39.74622007,  47.40152237,
        25.25783716,  18.76158591,  36.63666346,  65.09542941,
        70.73204006, -10.48038446,  24.09105081,  56.64836214,
        29.70733885,  49.09667794,  18.78409551,  37.28528736,
        27.81124618,  39.10344519, -12.9339052 ,  38.06784469,
        45.32829607,  19.11195264,  43.46006678, -25.71188402,
       -35.15515156,  50.40700674,  62.69078616,  11.67188758,
         3.98966214, -41.73577013,  61.94308169,  32.90035339,
        72.40854595,  -5.64716052,  -7.8692373 ,  81.491369  ,
        -4.56571859,  18.9463964 ,  16.10868898,  31.32709055,
        20.42820661,  31.9154953 ,  10.71012217,  -5.48171192,
       -20.26988525,  37.98761422,  35.47279038,  38.71

In [38]:
npdata=np.loadtxt('train.csv',delimiter=',',encoding='utf-8-sig')
test_data=np.loadtxt('test.csv',delimiter=',',encoding='utf-8-sig')
npdata.shape

(379, 14)

In [39]:
row,col=npdata.shape
x_in=npdata[:,:col-1]
y_in=npdata[:,col-1]

In [40]:
test_data.shape

(127, 13)

In [41]:
reg1=LinearRegression()
reg1.fit(x_in,y_in)

LinearRegression()

In [42]:
reg1.coef_,reg1.intercept_

(array([-0.93808077,  0.74103443,  0.01169157,  0.78087372, -2.1745575 ,
         2.35429653,  0.1233381 , -2.95232355,  2.53296817, -1.7029037 ,
        -2.25151962,  0.58835429, -4.26368155]),
 22.677233263858266)

In [43]:
y_in_pred=reg1.predict(test_data)

In [44]:
y_in_pred

array([12.43328344, 29.03367318, 22.37164455, 24.47778655, 20.60166977,
        2.72533175, 30.40000409, 24.86120042, 18.65724977, 23.53985838,
       24.11396872, 17.71143854, 17.44000298, 21.65356278, 42.31137694,
       23.84974493, 24.47573232, 27.53872655, 20.23606694, 31.15155453,
       23.78237904, 25.00979443, 33.95768541, 36.43515649, 32.04098329,
       16.71322632, 23.47176611, 32.93828009, 25.1807008 , 33.71008685,
       16.88580202, 26.02760837, 23.27040025, 25.47758968, 15.00946631,
       29.5857494 , 26.24821245, 20.37245654, 24.43681498,  9.44706894,
        8.38096654, 29.01392345, 29.59085403, 19.7575697 , 20.3719679 ,
        3.14442625, 39.52420118, 25.71741222, 30.37729628, 16.79453264,
       17.89088652, 41.02574533, 17.57238787, 20.89662584, 15.59837696,
       21.41394912, 18.4543645 , 23.1557639 , 13.67245022, 17.23573882,
       15.02710365, 29.15131353, 25.17166386, 25.49749375, 17.21186687,
       17.42936995, 34.70372763, 17.01340803, 27.10724289, 22.54

In [66]:
reg1.score(x_test,y_pred)

0.4158637166616541