**Implementing Gradient Descent for n featrue data set. df will be of (m*n)**

In [114]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [115]:
def slope(data,y,row,col,m,j):
    m_slope=0
    M=len(data)
    for i in range(row):
        y1=y[i]
        for k in range(col):
            m_slope+=(-2/M)*(y1-(m[k]*data[i][k]))*data[i][j]
    return m_slope        

In [116]:
def step_gd(data,y,row,col,m,lr):
    # x=data[:,:3]
    m_new=np.zeros(col)
    for j in range(col):
        m_new[j]=m[j]-lr*slope(data,y,row,col,m,j)
    return m_new    


In [117]:
def cost(data,y,m,row,col):
    M=len(data)
    total_cost=0
    for i in range(row):
        for j in range(col):
            total_cost+=(1/M)*(((y[i])-m[j]*data[i][j])**2)
    return total_cost

In [118]:
def gd(data,it,lr):
    row,col=data.shape
    m=np.zeros(col)
    y=data[:,col-1].copy()
    data[:,col-1]=np.ones(row)
    for i in range(it):
      m=step_gd(data,y,row,col,m,lr)
      print("Cost-:",cost(data,y,m,row,col))
    return m[:col-1],m[col-1]    
    

In [125]:
data_train=np.loadtxt('train.csv',delimiter=',',encoding='utf-8-sig')
learning_rate=0.00001
num_iterations=48
m,c=gd(data_train,num_iterations,learning_rate)
print(m,c)

Cost-: 8387.315340487983
Cost-: 8386.919041229705
Cost-: 8386.522870019899
Cost-: 8386.126826843329
Cost-: 8385.73091168463
Cost-: 8385.335124528627
Cost-: 8384.939465359987
Cost-: 8384.543934163406
Cost-: 8384.14853092365
Cost-: 8383.753255625525
Cost-: 8383.35810825364
Cost-: 8382.963088792818
Cost-: 8382.56819722783
Cost-: 8382.173433543308
Cost-: 8381.778797724066
Cost-: 8381.384289754875
Cost-: 8380.989909620472
Cost-: 8380.595657305628
Cost-: 8380.20153279508
Cost-: 8379.807536073584
Cost-: 8379.413667125937
Cost-: 8379.019925936856
Cost-: 8378.62631249116
Cost-: 8378.232826773583
Cost-: 8377.839468769012
Cost-: 8377.4462384621
Cost-: 8377.053135837656
Cost-: 8376.660160880472
Cost-: 8376.267313575407
Cost-: 8375.874593907138
Cost-: 8375.482001860522
Cost-: 8375.089537420345
Cost-: 8374.697200571425
Cost-: 8374.30499129855
Cost-: 8373.91290958655
Cost-: 8373.52095542016
Cost-: 8373.129128784232
Cost-: 8372.73742966361
Cost-: 8372.345858043072
Cost-: 8371.95441390749
Cost-: 8371.5

In [149]:
def predict(data,m,c):
    y_pred=np.zeros(len(data))
    for i in range(len(data)):
        y_pred[i]=((m*x[i,:]).sum()+c)
    return y_pred    

In [147]:
x_test=np.loadtxt('test.csv',delimiter=',',encoding='utf-8-sig')

In [150]:
y_pred=predict(x_test,m,c)

In [152]:
y_pred

array([ 0.66778385,  0.43266257, -0.30928953, -0.09785898,  0.46067581,
        0.91077189,  0.04254694,  0.12189817,  0.50868144,  1.10909237,
        0.49053078,  0.34936128,  0.92418278,  0.22677112,  0.02386365,
       -0.08214239,  0.42017409,  0.34643872,  0.31742481,  0.88778188,
        0.39396666,  0.71327749,  0.90335174,  0.63413931,  0.13283672,
        0.30452559, -0.32348526,  0.66408344,  0.72682315,  0.83153736,
        0.28467021, -0.04480647,  0.75733062,  0.39419373,  0.74044907,
       -0.69050275, -0.41351703, -0.01458797,  0.7271493 ,  0.44085232,
        0.23307144,  0.30336988,  0.41596248, -0.51618294,  0.11706346,
       -0.13333293,  0.40244849,  0.372526  , -0.22863938, -0.29137071,
       -0.27490195,  0.21032562,  0.41244852,  0.76834175,  0.79036702,
       -0.32298618,  0.57712371, -0.16955976,  0.70254572,  0.83945034,
       -0.053394  ,  0.06634019,  0.89320571, -0.29079394,  0.11522159,
        0.69165903,  0.40123704, -0.02613338, -0.17200043,  1.35

In [129]:
npdata=np.loadtxt('train.csv',delimiter=',',encoding='utf-8-sig')
test_data=np.loadtxt('test.csv',delimiter=',',encoding='utf-8-sig')
npdata.shape

(379, 14)

In [140]:
row,col=npdata.shape
x_in=npdata[:,:col-1]
y_in=npdata[:,col-1]

In [135]:
test_data.shape

(127, 13)

In [141]:
reg1=LinearRegression()
reg1.fit(x_in,y_in)

LinearRegression()

In [142]:
reg1.coef_,reg1.intercept_

(array([-0.93808077,  0.74103443,  0.01169157,  0.78087372, -2.1745575 ,
         2.35429653,  0.1233381 , -2.95232355,  2.53296817, -1.7029037 ,
        -2.25151962,  0.58835429, -4.26368155]),
 22.677233263858266)

In [143]:
y_in_pred=reg1.predict(test_data)

In [144]:
y_in_pred

array([12.43328344, 29.03367318, 22.37164455, 24.47778655, 20.60166977,
        2.72533175, 30.40000409, 24.86120042, 18.65724977, 23.53985838,
       24.11396872, 17.71143854, 17.44000298, 21.65356278, 42.31137694,
       23.84974493, 24.47573232, 27.53872655, 20.23606694, 31.15155453,
       23.78237904, 25.00979443, 33.95768541, 36.43515649, 32.04098329,
       16.71322632, 23.47176611, 32.93828009, 25.1807008 , 33.71008685,
       16.88580202, 26.02760837, 23.27040025, 25.47758968, 15.00946631,
       29.5857494 , 26.24821245, 20.37245654, 24.43681498,  9.44706894,
        8.38096654, 29.01392345, 29.59085403, 19.7575697 , 20.3719679 ,
        3.14442625, 39.52420118, 25.71741222, 30.37729628, 16.79453264,
       17.89088652, 41.02574533, 17.57238787, 20.89662584, 15.59837696,
       21.41394912, 18.4543645 , 23.1557639 , 13.67245022, 17.23573882,
       15.02710365, 29.15131353, 25.17166386, 25.49749375, 17.21186687,
       17.42936995, 34.70372763, 17.01340803, 27.10724289, 22.54

In [146]:
reg1.score(test_data,y_in_pred)

1.0