**Implementing Gradient Descent for n featrue data set. df will be of (m*n)**

In [57]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [76]:
def slope(data,y,row,col,m,j):
    m_slope=0
    M=len(data)
    for i in range(row):
        y1=y[i]
        for k in range(col):
            m_slope+=(-2/M)*(y1-(m[k]*data[i][k]))*data[i][j]
    return m_slope        

In [77]:
def step_gd(data,y,row,col,m,lr):
    # x=data[:,:3]
    m_new=np.zeros(col)
    for j in range(col):
        m_new[j]=m[j]-lr*slope(data,y,row,col,m,j)
    return m_new    


In [95]:
def cost(data,y,m,row,col):
    M=len(data)
    total_cost=0
    for i in range(row):
        for j in range(col):
            total_cost+=(1/M)*(((y[i])-m[j]*data[i][j])**2)
    return total_cost

In [96]:
def gd(data,it,lr):
    row,col=data.shape
    m=np.zeros(col)
    y=data[:,3].copy()
    data[:,3]=np.ones(row)
    for i in range(it):
      m=step_gd(data,y,row,col,m,lr)
      print("Cost-:",cost(data,y,m,row,col))
    return m[:col-1],m[col-1]    
    

In [102]:
data=np.loadtxt('data.csv',delimiter=',',encoding='utf-8-sig')
#data
learning_rate=0.00001
num_iterations=109
m,c=gd(data,num_iterations,learning_rate)
print(m,c)

Cost-: 8282.562121167644
Cost-: 8103.391323398729
Cost-: 7929.036514784782
Cost-: 7759.382618252061
Cost-: 7594.317178464237
Cost-: 7433.730303376764
Cost-: 7277.514607080641
Cost-: 7125.565153907283
Cost-: 6977.779403766809
Cost-: 6834.057158692681
Cost-: 6694.300510566205
Cost-: 6558.413789994997
Cost-: 6426.303516320063
Cost-: 6297.878348726731
Cost-: 6173.049038435196
Cost-: 6051.72838194695
Cost-: 5933.831175323923
Cost-: 5819.274169477674
Cost-: 5707.9760264463985
Cost-: 5599.857276638102
Cost-: 5494.840277018705
Cost-: 5392.849170224288
Cost-: 5293.809844577232
Cost-: 5197.649894986341
Cost-: 5104.298584711558
Cost-: 5013.686807974262
Cost-: 4925.747053394563
Cost-: 4840.413368237432
Cost-: 4757.621323449867
Cost-: 4677.307979471738
Cost-: 4599.41185280327
Cost-: 4523.872883312571
Cost-: 4450.6324022668905
Cost-: 4379.633101071731
Cost-: 4310.819000702234
Cost-: 4244.135421811612
Cost-: 4179.528955501761
Cost-: 4116.947434741447
Cost-: 4056.3399064178757
Cost-: 3997.656604007666

In [50]:
npdata=np.loadtxt('data.csv',delimiter=',',encoding='utf-8-sig')
npdata

array([[10., 12., 15., 45.],
       [11., 13., 16., 46.],
       [12., 14., 17., 47.]])

In [59]:
x=npdata[:,:3]
y=npdata[:,3]
x

array([[10., 12., 15.],
       [11., 13., 16.],
       [12., 14., 17.]])

In [60]:
reg1=LinearRegression()
reg1.fit(x,y)

LinearRegression()

In [67]:
reg1.coef_,reg1.intercept_

(array([0.33333333, 0.33333333, 0.33333333]), 32.66666666666667)