**Implementing Gradient Descent for n featrue data set. df will be of (m*n)**

In [57]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [76]:
def slope(data,y,row,col,m,j):
    m_slope=0
    M=len(data)
    for i in range(row):
        y1=y[i]
        for k in range(col):
            m_slope+=(-2/M)*(y1-(m[k]*data[i][k]))*data[i][j]
    return m_slope        

In [77]:
def step_gd(data,y,row,col,m,lr):
    # x=data[:,:3]
    m_new=np.zeros(col)
    for j in range(col):
        m_new[j]=m[j]-lr*slope(data,y,row,col,m,j)
    return m_new    


In [95]:
def cost(data,y,m,row,col):
    M=len(data)
    total_cost=0
    for i in range(row):
        for j in range(col):
            total_cost+=(1/M)*(((y[i])-m[j]*data[i][j])**2)
    return total_cost

In [96]:
def gd(data,it,lr):
    row,col=data.shape
    m=np.zeros(col)
    y=data[:,3].copy()
    data[:,3]=np.ones(row)
    for i in range(it):
      m=step_gd(data,y,row,col,m,lr)
      print("Cost-:",cost(data,y,m,row,col))
    return m[:col-1],m[col-1]    
    

In [104]:
data_train=np.loadtxt('train.csv',delimiter=',',encoding='utf-8-sig')
data_train.shape
#data
# learning_rate=0.00001
# num_iterations=109
# m,c=gd(data,num_iterations,learning_rate)
# print(m,c)

(379, 14)

In [50]:
npdata=np.loadtxt('data.csv',delimiter=',',encoding='utf-8-sig')
npdata

array([[10., 12., 15., 45.],
       [11., 13., 16., 46.],
       [12., 14., 17., 47.]])

In [59]:
x=npdata[:,:3]
y=npdata[:,3]
x

array([[10., 12., 15.],
       [11., 13., 16.],
       [12., 14., 17.]])

In [60]:
reg1=LinearRegression()
reg1.fit(x,y)

LinearRegression()

In [67]:
reg1.coef_,reg1.intercept_

(array([0.33333333, 0.33333333, 0.33333333]), 32.66666666666667)