In [1]:
import numpy as np

In [3]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T
x.shape,y.shape

((4, 2), (4, 1))

In [4]:
def sigmoid(z):
    return (1/1+np.exp(-z))

In [6]:
#Without any hidden layer
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weights,bias

(array([[-0.23020465],
        [ 0.22543307]]),
 array([0.47462098]))

In [7]:
output0=x
output=sigmoid(np.dot(output0,weights)+bias)

In [8]:
output

array([[1.62212081],
       [1.49655847],
       [1.78316151],
       [1.6250964 ]])

**Adding a hidden layer,, weights and bias will change**

In [15]:
#hidden layer weights and bias
wh=2*np.random.random((2,2))-1
bh=2*np.random.random((1,2))-1
wo=2*np.random.random((2,1))-1
bo=2*np.random.random((1,1))-1

In [16]:
output0=x
outputHidden=sigmoid(np.dot(output0,wh)+bh)
outputFinal=sigmoid(np.dot(outputHidden,wo)+bo)
outputFinal

array([[1.60563656],
       [1.10534701],
       [1.9388708 ],
       [1.21257686]])