In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[ 1., -1.,  2.],
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])

In [3]:
X_scaled = preprocessing.scale(X)
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [5]:
X_scaled.std(axis= 0)

array([1., 1., 1.])

**We should scale both training and testing data in same manner means the parameters of scaling should be same in both cases**

***But when we deploy our model it would have been already scaled on training data and when user gives it data to use it , then only the testing data comes, in this case scale() could handle this case, so StandardScaler() is used***

***StandardScaler(). fit() is used to scale the training data and store the parameters on which it scaled the train_data. when the testing data comes we use transform() and it would scale on the same parameters**

In [15]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [17]:
X_test = [[1,1,0]]
scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])