In [36]:
# def cost(x,y,m,c):
#     row,col=x.shape
#     cost_total=0
#     for i in range(row):
#         for j in range(col):
#             cost_total+=(1/row)*(y[i]-(m[j]*x[i][j])+c)
#     return cost_total     
# def find_slope(x,y,m,j):
#     m_slope=0
#     row=x.shape[0]
#     cols=x.shape[1]
#     M=x.shape[0]

#     for i in range(row):
#         for k in range(cols):
#             m_slope+=(-2/M)*(y[i]-m[k]*x[i][k])*x[i][j]
#     return m_slope    
# def step(x,y,lr,m):
#     row=x.shape[0]
#     cols=x.shape[1]
#     m_new=np.zeros(cols)
#     m_slope=0
#     for j in range(cols):
#         m_new[j]=m[j]-lr*find_slope(x,y,m,j)   
#     return m_new   
# def gd(x,y,lr,it,x_orig):
#     l=x.shape[1]
#     m=np.zeros(l)
#     c=m[l-1]
#     for i in range(it):
#         m=step(x,y,lr,m)
#         cost_n=cost(x_orig,y,m,c)
#         # print("Cost at it-:",cost_n,it)
#     return m    
# def predict(x,m):
#     n=x.shape[1]
#     c=m[n]
#     m_f = m[:13]
#     c_prod=np.dot(x,m_f)
#     return c_prod+c    
   

# def run():
#     x_test=data_test[:,:13]
    
    
#     rows, cols = x.shape
#     ones_column = np.ones((rows, 1), dtype=x.dtype)
#     X = np.concatenate((x, ones_column), axis=1)
#     iterations=15
#     learning_rate=0.001
#     m=gd(X,y,learning_rate,iterations,x)
#     y_pred=predict(x_test,m)
#     # print("M",m)
#     print(y_pred)
#     # print(X)
#     np.savetxt("predicted.csv",y_pred,delimiter=",",fmt='%.5f')
# run()    


In [37]:
import numpy as np
import pandas as pd

In [38]:
data_train=np.loadtxt("train.csv",delimiter=",")
data_test=np.loadtxt("test.csv",delimiter=",")


In [39]:
x_train=data_train[:,:4]
y_train=data_train[:,4]
x_test=data_test[:,:4]
print(x_train)
# print(y_train)
print(x_test)

[[   8.58   38.38 1021.03   84.37]
 [  21.79   58.2  1017.21   66.74]
 [  16.64   48.92 1011.55   78.76]
 ...
 [  29.8    69.34 1009.36   64.74]
 [  16.37   54.3  1017.94   63.63]
 [  30.11   62.04 1010.69   47.96]]
[[  11.95   42.03 1017.58   90.89]
 [  12.07   38.25 1012.67   81.66]
 [  26.91   74.99 1005.64   78.98]
 ...
 [  24.32   66.25 1009.09   91.89]
 [  23.49   42.8  1013.96   65.31]
 [  21.76   60.27 1018.96   85.06]]


In [40]:
def step_gd(x, y, learning_rate, m):
    M = len(x)

    m_slope = (-2 / M) * (((y - (x * m).sum(axis=1)).reshape(-1, 1)) * x).sum(axis=0)

    m = m - learning_rate * m_slope

    return m

In [41]:
def gd(x, y, learning_rate, num_iterations):
    m = np.zeros(len(x[0]))

    for i in range(num_iterations):
        m = step_gd(x, y, learning_rate, m)
        # c=m[-1]
        # cost_f=cost(x_train,y,m,c)
        # print("Cost At iteration",cost_f,i)

    return m

In [42]:
def run():
    learning_rate = 0.0000001
    num_iterations = 11
    df = pd.DataFrame(data_train)
    df[data_train.shape[1] - 1] = 1
    x = df.values
    # print(x.shape)
    m = gd(x, y_train, learning_rate, num_iterations)
    return m[0:-1], m[-1]

In [43]:
m, c = run()
m,c

(array([0.00768863, 0.02156496, 0.41011637, 0.02985613]),
 0.0004046524330582488)

In [44]:
def predict(x,m,c):
    # n=x.shape[1]
    # c=m[n-1]
    c_prod=np.dot(x,m)
    return c_prod+c   

In [45]:
# y_pred = np.zeros(len(data_test))
# for i in range(len(data_test)):
#     y_pred[i] = (m * data_test[i, :]).sum() + c
y_pred=predict(x_test,m,c)

In [46]:
y_pred

array([421.03849695, 418.66866053, 416.61192404, ..., 418.20387688,
       418.89548757, 421.89916666])

In [47]:
np.savetxt("predicted.csv",y_pred,delimiter=",",fmt='%.5f')