In [2]:
import numpy as np
import pandas as pd

In [7]:
# df_train = np.genfromtxt("../practice_2/data.csv", delimiter=",")
df_train=np.loadtxt('../practice_2/data.csv',delimiter=',',encoding='utf-8-sig')
df_test = np.genfromtxt("test.csv", delimiter=",")
df_train

array([[10., 12., 15., 45.],
       [11., 13., 16., 46.],
       [12., 14., 17., 47.]])

In [9]:
x_train = df_train[:, :3]
y_train = df_train[:, -1]
y_train

array([45., 46., 47.])

In [10]:
def step_gd(x, y, learning_rate, m):
    M = len(x)
    m_slope = (-2 / M) * (((y - (x * m).sum(axis=1)).reshape(-1, 1)) * x).sum(axis=0)

    m = m - learning_rate * m_slope

    return m

In [11]:
def gd(x, y, learning_rate, num_iterations):
    m = np.zeros(len(x[0]))

    for i in range(num_iterations):
        m = step_gd(x, y, learning_rate, m)

    return m

In [19]:
def run():
    learning_rate = 0.0001
    num_iterations = 100
    df = pd.DataFrame(df_train)
    df[df_train.shape[1] - 1] = 1
    x = df.values
    m = gd(x, y_train, learning_rate, num_iterations)
    return m[0:-1], m[-1]

In [20]:
m, c = run()
print(m,c)

[0.91738625 1.08915079 1.3467976 ] 0.08588226948164755


In [8]:
y_pred = np.zeros(len(df_test))

In [9]:
for i in range(len(df_test)):
    y_pred[i] = (m * df_test[i, :]).sum() + c

In [10]:
y_pred

array([12.42989444, 29.02039391, 22.37354643, 24.46703242, 20.62175438,
        2.73145008, 30.38110212, 24.85603445, 18.66257161, 23.53976431,
       24.11358439, 17.71638788, 17.46398303, 21.66356997, 42.31859907,
       23.85979426, 24.47528322, 27.55265382, 20.24532477, 31.16515999,
       23.80379308, 25.00538134, 33.95493979, 36.43002887, 32.04938087,
       16.70445641, 23.47622056, 32.95854932, 25.16710232, 33.71101947,
       16.89127364, 26.04023426, 23.2739599 , 25.4751929 , 15.0088932 ,
       29.59188242, 26.24833369, 20.39050928, 24.42398968,  9.44836666,
        8.37393997, 29.0090706 , 29.59695559, 19.76416454, 20.36709015,
        3.14047255, 39.52275699, 25.71759175, 30.35514265, 16.79149378,
       17.88628765, 41.00335586, 17.56938699, 20.91121754, 15.6030035 ,
       21.40397519, 18.45407138, 23.15688831, 13.67742577, 17.23112868,
       15.03166155, 29.15154152, 25.18664177, 25.49703011, 17.20547714,
       17.42690008, 34.70150774, 17.00983971, 27.09514313, 22.54

In [11]:
y_pred = np.around(y_pred, decimals=5)

file = np.savetxt("prediction.csv", y_pred, delimiter=", ")