Numpy Arrays 

In [2]:
import numpy as np

In [4]:
l=[1,2,3]
np.array(l)

array([1, 2, 3])

In [10]:
#np.zeros(dimension,dataType)
oneD=np.zeros(10,int)
twod=np.zeros((2,3),int)
print(oneD)
print(twod)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]]


In [13]:
twod.shape

(2, 3)

In [21]:
oneD[2:4]
print(twod[1,1])

0


In [18]:
arr=np.array((2,3))
arr

array([2, 3])