In [2]:
import numpy as np

**np.array(object,dtype)**

In [5]:
arr=np.array([10.2,2.5,6.7],dtype=int)
arr

array([10,  2,  6])

**ones(),zeros()**

In [7]:
one=np.ones((2,3),dtype=int)
one

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
zero=np.zeros((5,3),dtype=float)
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)**.

Return a new array of given shape and type, filled with fill_value.

In [11]:
answer=np.full((2,3),10,dtype=int)
answer

array([[10, 10, 10],
       [10, 10, 10]])

**np.empty()**-:

    numpy.empty(shape, dtype=float, order='C', *, like=None).
    
    This returns a new array of given shape and type, without initializing entries..

In [25]:
aray=np.empty((2,3),dtype=int)
aray

array([[  842120256,         411,           0],
       [          0,           1, -2147483648]])

**Note**-You will get a different result each time you execute using empty, as the array formed will always be uninitialised.

**numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)***

This returns evenly spaced values within a given interval.

In [31]:
# getData=np.arange(10)
getData=np.arange(1,10,3)
getData

array([1, 4, 7])

**numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]**

This returns evenly spaced numbers over a specified interval.

In [5]:
linArr=np.linspace(2,10,num=50,dtype=int)
linArr.data

In [44]:
#np.random.rand(d0,d1,d2....)
np.random.rand(2,3)

array([[0.69859762, 0.92268023, 0.17644173],
       [0.5422013 , 0.92318077, 0.42667487]])

In [47]:
# np.random.randint(low, high=None, size=None, dtype=int)
# np.random.randint(1,100,size=10)
np.random.randint(1,100,size=(2,4))

array([[65, 30, 80, 34],
       [37,  6, 56,  4]])

**Some Operations on np array**

In [71]:
a=np.random.randint(1,10,size=(2,2))
b=np.random.randint(1,5,size=(2,2))
print(a)
b

[[4 8]
 [6 2]]


array([[2, 2],
       [4, 1]])

In [77]:
# a.reshape(4,1)
# a/b
# a**b
c=np.transpose(a)
c

array([[4, 6],
       [8, 2]])

In [67]:
(a>b)
a>1

array([[ True,  True],
       [ True,  True]])

In [65]:
a==b

array([[False,  True],
       [False, False]])